spring:
  jwt.secret: ilovespringbootbecauseitiseasierthandjangodjangoisdifficulttosetupilovespringbootbecauseitiseasierthandjangodjangoisdifficulttosetup

  mail:
    host: smtp.gmail.com
    port: 587
    username: userid
    password: 1234

    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

  cache.type: redis
  redis.host: localhost
  redis.port: 6379