spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springDB?characterEncoding=UTF-8&serverTimezone=UTC
    username: username
    password: password

  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect